-- v75 免費資料源乾淨安裝 / 升級 SQL
-- 新 Supabase 專案：建議先跑 SQL_RUN_THIS_ONLY_v42.sql，再跑本檔。
-- 舊 Supabase 專案：可直接跑本檔，會補齊 v75 需要的資料中心欄位與表格。

create extension if not exists pgcrypto;
grant usage on schema public to anon, authenticated;

create table if not exists public.daily_games (
  id uuid primary key default gen_random_uuid(),
  game_date date not null default current_date,
  game_day_type text not null default 'today', -- yesterday / today / tomorrow
  game_status text not null default 'upcoming', -- upcoming / finished
  sport text,
  league text,
  game_time text,
  away text,
  home text,
  money text,
  spread text,
  total text,
  confidence integer[] default array[0,0,0],
  source_url text,
  source_name text default '資料中心',
  analysis_json jsonb default '{}'::jsonb,
  active boolean default true,
  updated_at timestamptz default now()
);

alter table public.daily_games add column if not exists game_date date default current_date;
alter table public.daily_games add column if not exists game_day_type text default 'today';
alter table public.daily_games add column if not exists game_status text default 'upcoming';
alter table public.daily_games add column if not exists sport text;
alter table public.daily_games add column if not exists league text;
alter table public.daily_games add column if not exists game_time text;
alter table public.daily_games add column if not exists away text;
alter table public.daily_games add column if not exists home text;
alter table public.daily_games add column if not exists money text;
alter table public.daily_games add column if not exists spread text;
alter table public.daily_games add column if not exists total text;
alter table public.daily_games add column if not exists confidence integer[] default array[0,0,0];
alter table public.daily_games add column if not exists source_url text;
alter table public.daily_games add column if not exists source_name text default '資料中心';
alter table public.daily_games add column if not exists analysis_json jsonb default '{}'::jsonb;
alter table public.daily_games add column if not exists active boolean default true;
alter table public.daily_games add column if not exists updated_at timestamptz default now();

-- 重新建立唯一鍵，確保 MLB/NBA/WNBA 的昨日/今日不互相覆蓋。
drop index if exists public.daily_games_unique_game_date_league_away_home_idx;
drop index if exists public.daily_games_v74_unique_idx;
drop index if exists public.daily_games_v75_unique_idx;
create unique index if not exists daily_games_v75_unique_idx
on public.daily_games (game_date, game_day_type, league, away, home, game_time);

create index if not exists daily_games_v75_query_idx
on public.daily_games (game_date, game_day_type, sport, league, active, game_status, game_time);

create table if not exists public.raw_sports_sync_runs (
  id uuid primary key default gen_random_uuid(),
  source text default 'github_actions',
  version text,
  status text,
  total_games integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.raw_sports_games (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.raw_sports_sync_runs(id) on delete cascade,
  game_date date,
  game_day_type text,
  game_status text,
  sport text,
  league text,
  game_time text,
  away text,
  home text,
  source_url text,
  raw_text text,
  parsed_json jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists raw_sports_games_v75_idx
on public.raw_sports_games (game_date, game_day_type, league, created_at desc);

create table if not exists public.daily_sync_status (
  id bigint generated by default as identity primary key,
  status text,
  message text,
  games_count int default 0,
  source text default 'github_actions',
  created_at timestamptz default now()
);

-- 只清掉今日資料，下一次 workflow 會用 v75 重新寫入。歷史 raw 會保留。
update public.daily_games
set active = false, updated_at = now()
where game_date >= current_date - interval '1 day';

alter table public.daily_games enable row level security;
alter table public.raw_sports_sync_runs enable row level security;
alter table public.raw_sports_games enable row level security;
alter table public.daily_sync_status enable row level security;

drop policy if exists "daily_games_select_all" on public.daily_games;
create policy "daily_games_select_all" on public.daily_games for select to anon, authenticated using (true);

drop policy if exists "raw_sports_sync_runs_select_all" on public.raw_sports_sync_runs;
create policy "raw_sports_sync_runs_select_all" on public.raw_sports_sync_runs for select to anon, authenticated using (true);

drop policy if exists "raw_sports_games_select_all" on public.raw_sports_games;
create policy "raw_sports_games_select_all" on public.raw_sports_games for select to anon, authenticated using (true);

drop policy if exists "daily_sync_status_select_all" on public.daily_sync_status;
create policy "daily_sync_status_select_all" on public.daily_sync_status for select to anon, authenticated using (true);

grant select on public.daily_games to anon, authenticated;
grant select on public.raw_sports_sync_runs to anon, authenticated;
grant select on public.raw_sports_games to anon, authenticated;
grant select on public.daily_sync_status to anon, authenticated;

-- 檢查結果
select 'daily_games' as table_name, count(*) as rows from public.daily_games
union all
select 'raw_sports_games', count(*) from public.raw_sports_games;
